server:
  port: 9000
Spring:
  cloud:
    gateway:
      routes:
       -id: first_route
        uri: http://baidu.com
        predicates:
          -Path: /first/**
      -id: second_route
        uri: http://baidu.com
        predicates:
          -Path: /second/**



